version: '3.8'

services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_DATABASE: 'bingo'
      MYSQL_USER: 'bingo'
      MYSQL_PASSWORD: 'bingotesting'
      MYSQL_ROOT_PASSWORD: 'rootbingotesting'
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always
  backend:
    build: .
    environment:
      - DB_HOST=mysql
    ports:
      - "3001:3001"
    restart: always
  frontend:
    image: frontend
    ports:
      - "3000:3000"
    restart: always
    
volumes:
  mysql_data:
